# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66967d01b8b64c75b64345f83c27aecc7f35d4601fd31443f6ba1dbebe37d5303dfe83f50503767d7d20fde46e5884a3d3018882387b7ea479083532d812540f

test:
  secret_key_base: 2ec76ca2fe262346c4ba414a8f42e32f317b21fa30e45fd8743db22e873321fd57caa8e23579208f8f733130675047b6a3385f747f05963905a3b0af0f001a46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
